### ISSUE TITLE
gzip exit error

### ISSUE THREAD

**Issue by tahz7** [tahz7/traffic_analyser#1]
```  File "<stdin>", line 1868, in <module>
  File "<stdin>", line 1854, in main
  File "<stdin>", line 792, in grab_log_data
  File "<stdin>", line 957, in get_data_from_logs
AttributeError: GzipFile instance has no attribute '__exit__'
```

Need to investigate this further, but it seems `with` statement doesn't work with gzip in python 2.6.

**Comment by tahz7** [comment]
https://github.com/tahz7/traffic_analyser/commit/92dab3b9c67f0c71bde82e2b9e9502bc84570d3c
